# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20160603_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 3, 15, 19, 17, 685909, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
