# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 11:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20160603_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=datetime.datetime(2016, 6, 6, 11, 5, 51, 595561, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
